# The URL the site will be built for
base_url = "https://shen-zhefeng.github.io/"
title = "Prototype Sam"
taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]
hard_link_static = true
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[languages.cn]
title = "Prototype Sam"

[languages.cn.translations]
home = "主页"
last_updated = "最后更新"
lang_en = "English"
lang_cn = "中文"
lang_ja = "日本語"
menu_name = "姓名"
menu_research = "研究"
menu_teaching = "教学"
menu_cv = "CV"
menu_more = "更多"
date_format = "%Y年%m月%d日"

[languages.ja]
title = "Prototype Sam"

[languages.ja.translations]
home = "ホーム"
last_updated = "最終更新"
lang_en = "English"
lang_cn = "中文"
lang_ja = "日本語"
menu_name = "名前"
menu_research = "研究"
menu_teaching = "教育"
menu_cv = "CV"
menu_more = "もっと"
date_format = "%Y年%m月%d日"

[translations]
home = "Start"
last_updated = "Last updated"
lang_en = "English"
lang_cn = "中文"
lang_ja = "日本語"
menu_name = "Name"
menu_research = "Research"
menu_teaching = "Teaching"
menu_cv = "CV"
menu_more = "More"
date_format = "%B %d, %Y"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola

[markdown.highlighting]
theme = "dark-plus"

[extra]
# Put all your custom variables here
show_word_count = false
show_reading_time = false

date_format = "%a %b %e, %Y"

home = "Start"

sam_menu = [
        { text = "Name", link = "/about" },
        { text = "Research", link = "/research" },
        { text = "Teaching", link = "/teaching" },
        { text = "CV", link = "/sample.pdf" },
        { text = "More", link = "/more" }
]

sam_bottom_menu = true
teaching_draft = false

[extra.sam_footer]
update_time=true
text = ""