base_url = "https://shen-zhefeng.github.io/"
title = "Zhefeng Shen"
taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]
hard_link_static = true


compile_sass = true


build_search_index = false

[extra]
# Put all your custom variables here
show_word_count = false
show_reading_time = false

date_format = "%a %b %e, %Y"

home = "home"

sam_menu = [
        { text = "Zhefeng Shen", link = "/about" },
        { text = "Research", link = "/research" },
        { text = "Teaching", link = "/teaching" },
        { text = "Others", link = "/others" }

]

sam_bottom_menu = true

[extra.sam_footer]
#text = "Who am I"
