name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          PAGES_BRANCH: gh-pages
          BUILD_ONLY: ${{ github.event_name == 'pull_request' }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
